### ISSUE TITLE
Error when deleting VHS entry

### ISSUE THREAD

**Issue by iPetk** [iPetk/vhs-frontend-lab#1]
When using a DELETE request to delete a VHS that doesn't have a thumbnail, server responds with 500 - works fine when deleting a VHS that has a thumbnail.

**WTR:**
Make a DELETE request for a VHS that doesn't have a thumbnail. Observe server response.

**Expected result:**
Server responds with 204, as it does when deleting a VHS with a thumbnail, deletes VHS.

**Actual result:**
Server responds with 500, "Internal server error", deletes VHS.

**Additional info:**

```
[Nest] 5084  - 11/22/2022, 11:58:24 AM   ERROR [ExceptionsHandler] The "path" argument must be of type string or an instance of Buffer or URL. Received null
TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at Object.unlink (node:fs:1752:10)
    at VhsService.deleteVhs (F:\Frontend\Projects\vhs-frontend-lab\vhs-backend\src\vhs\vhs.service.ts:62:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at F:\Frontend\Projects\vhs-frontend-lab\vhs-backend\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at F:\Frontend\Projects\vhs-frontend-lab\vhs-backend\node_modules\@nestjs\core\router\router-proxy.js:9:17
```

https://github.com/iPetk/vhs-frontend-lab/blob/373becf554635c30e4f6c69185267e9a479b5547/vhs-backend/src/vhs/vhs.service.ts#L62

**Comment by iPetk** [comment]
Bok @frle10 !
Ima mali bug u backendu, gore je opisano što se desi - pretpostavljam da samo treba dodati provjeru ako postoji thumbnail i onda bi trebalo biti sve okej.
To mogu ja napraviti i otvoriti PR, ili mogu pustiti vama :)

**Comment by frle10** [comment]
> Bok @frle10 ! Ima mali bug u backendu, gore je opisano što se desi - pretpostavljam da samo treba dodati provjeru ako postoji thumbnail i onda bi trebalo biti sve okej. To mogu ja napraviti i otvoriti PR, ili mogu pustiti vama :)

Ups, moje isprike :) Vidim problem. Thumbnail nismo imali dosad u backendu pa sam ga u jedan dan dodao da možeš što prije dobiti zadatak i pobjeglo je.

Vidim da se dobro snalaziš i u backendu, primijetio sam i commit s dodavanjem CORS-a. Pohvala :+1: 

Ako ti nije problem, možeš i ti dodati malu provjeru i to je to. :)  Hvala ti!
