### ISSUE TITLE
Improve Header component

### ISSUE THREAD

**Issue by frle10** [iPetk/vhs-frontend-lab#4]
https://github.com/iPetk/vhs-frontend-lab/blob/e6e866e97b62ec364d223dfb4d702e42594be384/vhs-frontend/src/components/Header.tsx#L1-L14

Remove `Props` if not used. If used, make it an interface instead of type.
Additionally, links are separated with a `<br>` tag, let's change that and make a flex container with horizontal direction and beautify the navbar with CSS. :)

**Comment by iPetk** [comment]
Merged :sparkles:
